#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from std_msgs.msg import String
import time

class LCDPublisher(Node):
    def __init__(self):
        super().__init__('lcd_publisher')
        self.publisher_ = self.create_publisher(String, 'lcd_data', 10)
        timer_period = 1.0  # seconds
        self.timer = self.create_timer(timer_period, self.timer_callback)
        self.get_logger().info('LCD Publisher Node started')
        
        # Thông tin cần hiển thị
        self.message_lines = [
            "Nhom 5",
            "Nguyen Long Hoang An",
            "Le Ngoc Bao Kha",
            "Mai Quoc Huy"
        ]
        
    def timer_callback(self):
        msg = String()
        
        # Đóng gói tất cả các dòng vào một chuỗi, ngăn cách bởi dấu |
        msg.data = "|".join(self.message_lines)
        
        self.publisher_.publish(msg)
        self.get_logger().info(f'Publishing: "{msg.data}"')


def main(args=None):
    rclpy.init(args=args)
    lcd_publisher = LCDPublisher()
    
    try:
        rclpy.spin(lcd_publisher)
    except KeyboardInterrupt:
        pass
    finally:
        lcd_publisher.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()